# Generated by Django 4.2 on 2025-11-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomno', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('fees', models.IntegerField()),
                ('address', models.CharField(max_length=30)),
            ],
        ),
    ]
